# -*- coding: utf-8 -*-
"""
Created on Mon Jul 20 09:03:15 2026

@author: eric

Columns
image_id, filename, favorited, favorited_at, times_displayed, liked

cursor.execute('SELECT name FROM pragma_table_info("favorites")')
"""

import sqlite3
import pandas as pd
from sd_parsers import ParserManager
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from wordcloud import WordCloud
import re
#import numpy as np

##########
# Alter Table
##########

# Connect to the database
conn = sqlite3.connect('favorites.db')
cursor = conn.cursor()

column_name = 'prompt_words_selected'
# Add the new column
try:
    cursor.execute(f'ALTER TABLE favorites ADD COLUMN {column_name} TEXT')
    conn.commit()
    print(f"Column '{column_name}' added successfully!")
except sqlite3.OperationalError as e:
    if "duplicate column name" in str(e):
        print(f"Column '{column_name}' already exists")
    else:
        print(f"Error: {e}")

# Close connection
conn.close()

##########
# Favorite count
##########
conn = sqlite3.connect('favorites.db')
cursor = conn.cursor()

# Get the count
cursor.execute("SELECT COUNT(*) FROM favorites WHERE favorited = 1")
favorite = cursor.fetchone()[0]

cursor.execute("SELECT COUNT(*) FROM favorites")
total = cursor.fetchone()[0]

print(f"Number of favorited images: {favorite}/{total}")

# Close the connection
conn.close()

##########
conn = sqlite3.connect('favorites.db')
cursor = conn.cursor()

cursor.execute("SELECT * FROM favorites where favorited = 1 limit 1")
rows = cursor.fetchall()
image_path_list = []

for row in rows:
    image_path_list.append(row[1])
    print(row)

# Close the connection
conn.close()

#########
# find tags of single image from filename
#########
#photo_id = '13406--1897453673.png'

conn = sqlite3.connect('favorites.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM favorites where favorited = 1 limit 1")
photo_path = cursor.fetchone()[1]
conn.close()

# Initialize the parser manager
parser_manager = ParserManager()

# Initialize empty list to store parsed data
parsed_data = []

prompt_info = parser_manager.parse(photo_path)

# to string
prompt_string = prompt_info.full_prompt if hasattr(prompt_info, 'full_prompt') else ''
prompt_string = prompt_string + ',, ,'
prompt_string = prompt_string.strip()

while True:
        collapsed = re.sub(r',\s*,', ',', prompt_string)
        if collapsed == prompt_string:
            break
        prompt_string = collapsed
        
prompt_string = re.sub(r',+$', '', prompt_string)

re.sub(r',\s*(?!$)', ', ', prompt_string)

# not converting to list yet
# convert to list, separate by comma
#prompt_list = [item.strip() for item in prompt_string.split(',')]

# remove empty rows
#prompt_list = [item for item in prompt_list if item]

######
# update column
######
conn = sqlite3.connect('favorites.db')
cursor = conn.cursor()

# Make sure autocommit is enabled or commit manually
cursor.execute("UPDATE favorites SET liked = 0")
conn.commit()  # DON'T FORGET THIS!

# Or use autocommit mode (sqlite3 3.12+)
# conn = sqlite3.connect('favorites.db', isolation_level=None)

conn.close()

# Single image
# parser_manager = ParserManager()
# prompt_info = parser_manager.parse("E:/Images/txt2img-images/static/1/13406--1897453673.png")

# if prompt_info:
#     print(f"Image generated by: {prompt_info.models}")
#     print(f"Full Prompt: {prompt_info.full_prompt}")
#     print(f"Negative Prompt: {prompt_info.full_negative_prompt}")
    
#     # Access specific sampler parameters
#     if prompt_info.samplers:
#         sampler = prompt_info.samplers[0]
#         print(f"Sampler: {sampler.name}")
#         print(f"Parameters: {sampler.parameters}") # Includes cfg_scale, seed, steps, etc.
# else:
#     print("Could not parse any known AI metadata from the image.")

# models = prompt_info.models
# for model in models:
#             # The model name will be printed here
#             print(f"Checkpoint: {model.name}")

##################
# parse image meta data to DataFrame
##################

generic_words = ['extreme detail', 'photorealistic', 'detailed', 
                  'high detailed skin', 'raw photo', 'breathtaking', 
                  'ultra high res', 'masterpiece', 'super detail', 
                  'shallow depth of field', 'film', 'best quality', 
                  'cinematic film still', 'realistic', 'hd', '8k uhd', 
                  'professional', 'professional photography', 'cinemascope', 
                  'oc rendering', 'fujifilm xt3', 'high quality', 
                  'cinematic photo', 'highly detailed', '35mm photograph', 
                  'cinematic', 'dslr', 'movie still', 'portrait',
                  'hyperdetailed photography', 'cinematic lighting', 
                  'cinematic shot', 'film still', '8k']

shape_words = ['stunning woman', 'beautiful woman', 'sexy woman', 
               'slutty woman', 'large breasts', 'large ass', 'huge breasts', 
               'huge ass', 'large butt', 'large tits', 'huge tits',
               'huge exposed breasts', 'huge butt', 'wide ass', 'medium ass',
               'wide butt', 'wide hips', 'medium breasts', 'medium butt',
               'bursting breasts']

# load all favorited images
conn = sqlite3.connect('favorites.db')
cursor = conn.cursor()

cursor.execute("SELECT * FROM favorites where favorited = 1")
rows = cursor.fetchall()
image_path_list = []

for row in rows:
    image_path_list.append(row[1])
    #print(row)

# Close the connection
conn.close()

# Initialize the parser manager
parser_manager = ParserManager()

# Initialize empty list to store parsed data
parsed_data = []

# Parse each image
for image_path in image_path_list:
    try:
        # Parse the image metadata using ParserManager
        prompt_info = parser_manager.parse(image_path)
        
        # Check if parsing was successful
        if prompt_info:
            # Extract checkpoint/model names
            checkpoint_names = []
            if hasattr(prompt_info, 'models') and prompt_info.models:
                for model in prompt_info.models:
                    checkpoint_names.append(model.name)
                checkpoint_name = ', '.join(checkpoint_names)
            else:
                checkpoint_name = ''
            
            # Extract sampler information
            sampler_name = ''
            cfg_scale = ''
            steps = ''
            seed = ''
            
            if hasattr(prompt_info, 'samplers') and prompt_info.samplers:
                sampler = prompt_info.samplers[0]  # Get first sampler
                sampler_name = sampler.name if hasattr(sampler, 'name') else ''
                
                # Extract parameters from the sampler's parameters dictionary
                if hasattr(sampler, 'parameters') and sampler.parameters:
                    params = sampler.parameters
                    cfg_scale = params.get('cfg_scale', '')
                    steps = params.get('steps', '')
                    seed = params.get('seed', '')
                    # Also try alternative parameter names if they exist
                    if not cfg_scale:
                        cfg_scale = params.get('cfg', '')
                    if not steps:
                        steps = params.get('step', '')
            
            # Build the row data
            row = {
                'file_name': Path(image_path).name,
                'file_path': image_path,
                'full_prompt': prompt_info.full_prompt if hasattr(prompt_info, 'full_prompt') else '',
                'full_negative_prompt': prompt_info.full_negative_prompt if hasattr(prompt_info, 'full_negative_prompt') else '',
                'checkpoint_name': checkpoint_name,
                'sampler': sampler_name,
                'cfg_scale': cfg_scale,
                'steps': steps,
                'seed': seed
            }
            
            parsed_data.append(row)
            print(f"✓ Successfully parsed: {Path(image_path).name}")
            
        else:
            print(f"✗ No metadata found for: {image_path}")
            parsed_data.append({
                'file_name': Path(image_path).name,
                'file_path': image_path,
                'full_prompt': 'NO_METADATA',
                'full_negative_prompt': 'NO_METADATA',
                'checkpoint_name': 'NO_METADATA',
                'sampler': 'NO_METADATA',
                'cfg_scale': 'NO_METADATA',
                'steps': 'NO_METADATA',
                'seed': 'NO_METADATA'
            })
            
    except Exception as e:
        print(f"✗ Error parsing {image_path}: {e}")
        parsed_data.append({
            'file_name': Path(image_path).name,
            'file_path': image_path,
            'full_prompt': f'ERROR: {str(e)}',
            'full_negative_prompt': f'ERROR: {str(e)}',
            'checkpoint_name': 'ERROR',
            'sampler': 'ERROR',
            'cfg_scale': 'ERROR',
            'steps': 'ERROR',
            'seed': 'ERROR'
        })

# Convert to DataFrame
df = pd.DataFrame(parsed_data)

# remove files with missing metadata
df = df[~df['full_prompt'].isin(['NO_METADATA', 'ERROR'])]

# Display the DataFrame
print("\n" + "="*80)
print(f"✅ DataFrame created successfully with {len(df)} rows!")
print("="*80)
print(df)

# Optionally save to CSV
df.to_csv('stable_diffusion_metadata.csv', index=False)
print("\n💾 Data saved to 'stable_diffusion_metadata.csv'")

#############################

# load from disk
# Assuming df is your existing DataFrame
df = pd.read_csv('stable_diffusion_metadata.csv')  # if loading from file

# ============================================================================
# 1. CROSS-TABULATION TABLE: Checkpoint vs Sampler Counts
# ============================================================================

# Create contingency table
cross_tab = pd.crosstab(df['checkpoint_name'], df['sampler'], margins=True)

print("="*80)
print("CHECKPOINT vs SAMPLER - IMAGE COUNTS")
print("="*80)
print(cross_tab)

# Visualize as heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(cross_tab.iloc[:-1, :-1],  # Exclude margins
            annot=True, 
            fmt='d', 
            cmap='YlOrRd',
            cbar_kws={'label': 'Number of Images'})
plt.title('Distribution of Images by Checkpoint and Sampler', fontsize=14, fontweight='bold')
plt.xlabel('Sampler', fontsize=12)
plt.ylabel('Checkpoint', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig('checkpoint_sampler_heatmap.png', dpi=300, bbox_inches='tight')
plt.show()

# ============================================================================
# 2. PROCESS PROMPT WORDS (Helper function)
# ============================================================================

# TODO
# this version does not have filtering to include/exclude generic/shape words
def process_prompt_words(df, column_name, top_n=30, min_word_length=2):
    """
    Process comma-separated prompt strings, deduplicate words within each prompt,
    and count frequency across all images.
    """
    all_words = []
    # things to exclude 
    # beret, crown, doughnut
    
    # added as globals above, need to make sure it works
    # generic_words = ['extreme detail', 'photorealistic', 'detailed', 
    #                   'high detailed skin', 'raw photo', 'breathtaking', 
    #                   'ultra high res', 'masterpiece', 'super detail', 
    #                   'shallow depth of field', 'film', 'best quality', 
    #                   'cinematic film still', 'realistic', 'hd', '8k uhd', 
    #                   'professional', 'professional photography', 'cinemascope', 
    #                   'oc rendering', 'fujifilm xt3', 'high quality', 
    #                   'cinematic photo', 'highly detailed', '35mm photograph', 
    #                   'cinematic', 'dslr', 'movie still', 'portrait',
    #                   'hyperdetailed photography', 'cinematic lighting', 
    #                   'cinematic shot', 'film still', '8k']
    
    # shape_words = ['stunning woman', 'beautiful woman', 'sexy woman', 
    #                'slutty woman', 'large breasts', 'large ass', 'huge breasts', 
    #                'huge ass', 'large butt', 'large tits', 'huge tits',
    #                'huge exposed breasts', 'huge butt', 'wide ass', 'medium ass',
    #                'wide butt', 'wide hips', 'medium breasts', 'medium butt',
    #                'bursting breasts']
       
    for prompt_text in df[column_name].dropna():
        if prompt_text and prompt_text != 'NO_METADATA' and not prompt_text.startswith('ERROR'):
            # Split by comma and clean each word
            words = [w.strip().lower() for w in str(prompt_text).split(',') if w.strip()]
            # Deduplicate within this prompt
            unique_words = list(set(words))
            all_words.extend(unique_words)
    
    # Count frequencies
    word_counts = Counter(all_words)
    
    # Filter out words that are too short or common noise
    filtered_counts = {word: count for word, count in word_counts.items() 
                      if len(word) >= min_word_length #and word not in ['', ' ', 'and', 'the', 'of', 'for']
                          and word not in generic_words
                          and word not in shape_words
                      }
    
   # Sort by frequency
    sorted_words = sorted(filtered_counts.items(), key=lambda x: x[1], reverse=True)
    
    return sorted_words[:top_n]

# ============================================================================
# 3. FULL PROMPT - Word Frequency Visualization
# ============================================================================

print("\n" + "="*80)
print("FULL PROMPT - Top Words")
print("="*80)

# Process full prompts
top_full_prompt_words = process_prompt_words(df, 'full_prompt', top_n=30)

# Display as DataFrame
full_prompt_df = pd.DataFrame(top_full_prompt_words, columns=['Word', 'Count'])
print(full_prompt_df.to_string(index=False))

# Bar chart for full prompt words
fig, ax = plt.subplots(figsize=(14, 10))
words, counts = zip(*top_full_prompt_words)
bars = ax.barh(words, counts, color='skyblue', edgecolor='navy', linewidth=1)
ax.set_xlabel('Frequency (Number of Images)', fontsize=12)
ax.set_title('Top 30 Most Frequent Words in Full Prompts', fontsize=14, fontweight='bold')
ax.invert_yaxis()  # Most frequent at top
ax.grid(axis='x', alpha=0.3)
ax.set_axisbelow(True)

# Add value labels on bars
for bar, count in zip(bars, counts):
    width = bar.get_width()
    ax.text(width, bar.get_y() + bar.get_height()/2, 
            f' {count}', ha='left', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('full_prompt_word_frequency.png', dpi=300, bbox_inches='tight')
plt.show()

# Word cloud for full prompts
# plt.figure(figsize=(14, 10))
# wordcloud_full = WordCloud(width=800, height=600, 
#                           background_color='white',
#                           colormap='viridis',
#                           max_words=100,
#                           min_font_size=10).generate_from_frequencies(
#                               dict(top_full_prompt_words)
#                           )
# plt.imshow(wordcloud_full, interpolation='bilinear')
# plt.axis('off')
# plt.title('Full Prompt Word Cloud', fontsize=14, fontweight='bold', pad=20)
# plt.tight_layout()
# plt.savefig('full_prompt_wordcloud.png', dpi=300, bbox_inches='tight')
# plt.show()

# ============================================================================
# 4. NEGATIVE PROMPT - Word Frequency Visualization
# ============================================================================

print("\n" + "="*80)
print("NEGATIVE PROMPT - Top Words")
print("="*80)

# Process negative prompts
top_neg_prompt_words = process_prompt_words(df, 'full_negative_prompt', top_n=30)

# Display as DataFrame
neg_prompt_df = pd.DataFrame(top_neg_prompt_words, columns=['Word', 'Count'])
print(neg_prompt_df.to_string(index=False))

# Bar chart for negative prompt words
fig, ax = plt.subplots(figsize=(14, 10))
words, counts = zip(*top_neg_prompt_words) if top_neg_prompt_words else ([], [])
bars = ax.barh(words, counts, color='salmon', edgecolor='darkred', linewidth=1)
ax.set_xlabel('Frequency (Number of Images)', fontsize=12)
ax.set_title('Top 30 Most Frequent Words in Negative Prompts', fontsize=14, fontweight='bold')
ax.invert_yaxis()  # Most frequent at top
ax.grid(axis='x', alpha=0.3)
ax.set_axisbelow(True)

# Add value labels on bars
for bar, count in zip(bars, counts):
    width = bar.get_width()
    ax.text(width, bar.get_y() + bar.get_height()/2, 
            f' {count}', ha='left', va='center', fontsize=9)

plt.tight_layout()
plt.savefig('negative_prompt_word_frequency.png', dpi=300, bbox_inches='tight')
plt.show()

# Word cloud for negative prompts
if top_neg_prompt_words:
    plt.figure(figsize=(14, 10))
    wordcloud_neg = WordCloud(width=800, height=600, 
                             background_color='white',
                             colormap='Reds',
                             max_words=100,
                             min_font_size=10).generate_from_frequencies(
                                 dict(top_neg_prompt_words)
                             )
    plt.imshow(wordcloud_neg, interpolation='bilinear')
    plt.axis('off')
    plt.title('Negative Prompt Word Cloud', fontsize=14, fontweight='bold', pad=20)
    plt.tight_layout()
    plt.savefig('negative_prompt_wordcloud.png', dpi=300, bbox_inches='tight')
    plt.show()

# ============================================================================
# 5. SUMMARY STATISTICS
# ============================================================================

print("\n" + "="*80)
print("SUMMARY STATISTICS")
print("="*80)

print(f"Total images analyzed: {len(df)}")
print(f"Unique checkpoints: {df['checkpoint_name'].nunique()}")
print(f"Unique samplers: {df['sampler'].nunique()}")

# Top checkpoints
print("\nTop 5 Checkpoints:")
print(df['checkpoint_name'].value_counts().head(5).to_string())

# Top samplers
print("\nTop 5 Samplers:")
print(df['sampler'].value_counts().head(5).to_string())

# Average steps
if 'steps' in df.columns:
    avg_steps = pd.to_numeric(df['steps'], errors='coerce').mean()
    print(f"\nAverage steps: {avg_steps:.1f}")

# Average CFG scale
if 'cfg_scale' in df.columns:
    avg_cfg = pd.to_numeric(df['cfg_scale'], errors='coerce').mean()
    print(f"Average CFG scale: {avg_cfg:.2f}")

# ============================================================================
# 6. ADVANCED: Top words by checkpoint (optional)
# ============================================================================

def top_words_by_group(df, group_col, prompt_col, top_n=10):
    """Show top words for each checkpoint/sampler group"""
    results = {}
    for group in df[group_col].unique():
        if group and group != 'NO_METADATA' and not str(group).startswith('ERROR'):
            subset = df[df[group_col] == group]
            top_words = process_prompt_words(subset, prompt_col, top_n=top_n)
            results[group] = top_words
    return results

# Uncomment to see top words per checkpoint
# top_by_checkpoint = top_words_by_group(df, 'checkpoint_name', 'full_prompt', top_n=10)
# for checkpoint, words in top_by_checkpoint.items():
#     print(f"\n{checkpoint}:")
#     for word, count in words[:5]:
#         print(f"  {word}: {count}")

print("\n" + "="*80)
print("✅ Visualizations complete! Check saved PNG files.")
print("="*80)

# ============================================================================
# 0. PROCESS PROMPT WORDS (Helper function) with percentages
# ============================================================================
def process_prompt_words_with_percentage(df, column_name, top_n=30, min_word_length=2, generic=True, shape=True):
    """
    Process comma-separated prompt strings, deduplicate words within each prompt,
    count frequency, and calculate percentage of total images.
    """
    total_images = len(df)
    all_words = []
    
    # repeated from above in the non-percent version
    # generic_words = ['extreme detail', 'photorealistic', 'detailed', 
    #                   'high detailed skin', 'raw photo', 'breathtaking', 
    #                   'ultra high res', 'masterpiece', 'super detail', 
    #                   'shallow depth of field', 'film', 'best quality', 
    #                   'cinematic film still', 'realistic', 'hd', '8k uhd', 
    #                   'professional', 'professional photography', 'cinemascope', 
    #                   'oc rendering', 'fujifilm xt3', 'high quality', 
    #                   'cinematic photo', 'highly detailed', '35mm photograph', 
    #                   'cinematic', 'dslr', 'movie still', 'portrait',
    #                   'hyperdetailed photography', 'cinematic lighting', 
    #                   'cinematic shot', 'film still', '8k']
    
    # shape_words = ['stunning woman', 'beautiful woman', 'sexy woman', 
    #                 'slutty woman', 'large breasts', 'large ass', 'huge breasts', 
    #                 'huge ass', 'large butt', 'large tits', 'huge tits',
    #                 'huge exposed breasts', 'huge butt', 'wide ass', 'medium ass',
    #                 'wide butt', 'wide hips', 'medium breasts', 'medium butt',
    #                 'bursting breasts']
    
    for prompt_text in df[column_name].dropna():
        if prompt_text and prompt_text != 'NO_METADATA' and not str(prompt_text).startswith('ERROR'):
            # Split by comma and clean each word
            words = [w.strip().lower() for w in str(prompt_text).split(',') if w.strip()]
            # Deduplicate within this prompt
            unique_words = list(set(words))
            all_words.extend(unique_words)
    
    # Count frequencies
    word_counts = Counter(all_words)
    
    # Filter out words based on keyword lists
    if (generic == True and shape == True):
        filtered_counts = {word: count for word, count in word_counts.items() 
                          if len(word) >= min_word_length
                              and word not in generic_words
                              and word not in shape_words
                          }
    elif (generic == False and shape == True):
        filtered_counts = {word: count for word, count in word_counts.items() 
                          if len(word) >= min_word_length
                              and word not in shape_words
                          }
    elif (generic == True and shape == False):
        filtered_counts = {word: count for word, count in word_counts.items() 
                          if len(word) >= min_word_length
                              and word not in generic_words
                          }
    else:
        filtered_counts = {word: count for word, count in word_counts.items() 
                          if len(word) >= min_word_length
                          }

    # Calculate percentages
    word_data = []
    for word, count in filtered_counts.items():
        percentage = (count / total_images) * 100
        word_data.append({
            'word': word,
            'count': count,
            'percentage': percentage,
            'percentage_formatted': f"{percentage:.1f}%"
        })
    
    # Sort by count (frequency)
    word_data = sorted(word_data, key=lambda x: x['count'], reverse=True)
    
    return word_data[:top_n]

# ============================================================================
# 1. FULL PROMPT - Words with Percentages
# ============================================================================

print("="*80)
print("FULL PROMPT - Word Frequency with Percentages")
print("="*80)

# top 150, 2 letters or more, generic filter, shape filter
top_full_prompt_data = process_prompt_words_with_percentage(df, 'full_prompt', 300, 2, True, True)

# Display as DataFrame
full_prompt_df = pd.DataFrame(top_full_prompt_data)
print(full_prompt_df.to_string(index=False))

# ============================================================================
# 2. NEGATIVE PROMPT - Words with Percentages
# ============================================================================

print("\n" + "="*80)
print("NEGATIVE PROMPT - Word Frequency with Percentages")
print("="*80)

top_neg_prompt_data = process_prompt_words_with_percentage(df, 'full_negative_prompt', top_n=30)

# Display as DataFrame
neg_prompt_df = pd.DataFrame(top_neg_prompt_data)
print(neg_prompt_df.to_string(index=False))

# ============================================================================
# 3. VISUALIZATION - Horizontal Bar Chart with Percentages
# ============================================================================

# Function to create percentage bar chart
def create_percentage_bar_chart(data, title, filename, color):
    """Create a horizontal bar chart showing percentages"""
    words = [item['word'] for item in data]
    percentages = [item['percentage'] for item in data]
    counts = [item['count'] for item in data]
    
    fig, ax = plt.subplots(figsize=(14, 10))
    bars = ax.barh(words, percentages, color=color, edgecolor='black', linewidth=0.5)
    
    ax.set_xlabel('Percentage of Images (%)', fontsize=12, fontweight='bold')
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.invert_yaxis()  # Most frequent at top
    ax.grid(axis='x', alpha=0.3)
    ax.set_axisbelow(True)
    
    # Add labels with both percentage and count
    for bar, count, pct in zip(bars, counts, percentages):
        width = bar.get_width()
        ax.text(width + 0.5, bar.get_y() + bar.get_height()/2, 
                f'{pct:.1f}% ({count})', 
                ha='left', va='center', fontsize=9, fontweight='bold')
    
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    plt.show()

# Create charts with percentages
create_percentage_bar_chart(
    top_full_prompt_data, 
    'Top 30 Most Frequent Words in Full Prompts\n(Percentage of Total Images)', 
    'full_prompt_percentage.png', 
    'skyblue'
)

create_percentage_bar_chart(
    top_neg_prompt_data, 
    'Top 30 Most Frequent Words in Negative Prompts\n(Percentage of Total Images)', 
    'negative_prompt_percentage.png', 
    'salmon'
)

# ============================================================================
# 4. TABLE WITH PERCENTAGES (Styled for better readability)
# ============================================================================

# Create styled tables with percentage bars
def styled_percentage_table(data, title):
    """Create a styled DataFrame with percentage bars"""
    df_display = pd.DataFrame(data)
    
    # Create a simple text-based bar chart in the table
    max_pct = df_display['percentage'].max() if not df_display.empty else 1
    df_display['bar'] = df_display['percentage'].apply(
        lambda x: '█' * int((x / max_pct) * 30) if x > 0 else ''
    )
    
    print(f"\n{title}")
    print("="*80)
    print(f"{'Word':<20} {'Count':>8} {'Percentage':>12} {'Bar':<35}")
    print("-"*80)
    for _, row in df_display.iterrows():
        print(f"{row['word']:<20} {row['count']:>8} {row['percentage_formatted']:>12} {row['bar']}")
    print("="*80)

# Display styled tables
styled_percentage_table(top_full_prompt_data, "FULL PROMPT WORD FREQUENCY")
styled_percentage_table(top_neg_prompt_data, "NEGATIVE PROMPT WORD FREQUENCY")

# ============================================================================
# 5. SUMMARY STATISTICS
# ============================================================================

print("\n" + "="*80)
print("SUMMARY - PERCENTAGE STATISTICS")
print("="*80)

total_images = len(df)
print(f"Total images analyzed: {total_images}")

if top_full_prompt_data:
    print(f"\nFull Prompt - Most common word: '{top_full_prompt_data[0]['word']}' "
          f"appears in {top_full_prompt_data[0]['percentage']:.1f}% of images")
    
    # Count words that appear in certain percentage ranges
    high_pct = sum(1 for x in top_full_prompt_data if x['percentage'] > 50)
    med_pct = sum(1 for x in top_full_prompt_data if 20 < x['percentage'] <= 50)
    low_pct = sum(1 for x in top_full_prompt_data if x['percentage'] <= 20)
    print(f"  - {high_pct} words appear in >50% of images")
    print(f"  - {med_pct} words appear in 20-50% of images")
    print(f"  - {low_pct} words appear in <20% of images")

if top_neg_prompt_data:
    print(f"\nNegative Prompt - Most common word: '{top_neg_prompt_data[0]['word']}' "
          f"appears in {top_neg_prompt_data[0]['percentage']:.1f}% of images")

# ============================================================================
# 6. EXPORT TO CSV WITH PERCENTAGES
# ============================================================================

# Save to CSV with percentages
full_prompt_df.to_csv('full_prompt_percentages.csv', index=False)
neg_prompt_df.to_csv('negative_prompt_percentages.csv', index=False)
print(f"\n✅ Percentage data saved to 'full_prompt_percentages.csv' and 'negative_prompt_percentages.csv'")